### PR TITLE
Built files are in build dir, not source dir

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
Are you building with your prefer 32bit patch? I get 

```
Couldn't find 'usr/bin/nwam-manager-properties' in any of the specified search directories:
        /ws/toasty/oi-userland/components/openindiana/nwam-manager
        /ws/toasty/oi-userland/components/openindiana/nwam-manager/build
        /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386
        /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/mangled
```

But i have files in the `i86` subdirectory

```
ls -alh $WORKSPACE/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/usr/bin/i86/
total 6
drwxr-xr-x   2 toasty   builders       3 Aug 22 17:55 .
drwxr-xr-x   3 toasty   builders       3 Aug 22 17:51 ..
-rwxr-xr-x   1 toasty   builders   1.16K Aug 22 17:55 nwam-manager-properties
```

**Comment by mtelka** [comment]
> Are you building with your prefer 32bit patch? I get
> 
> ```
> Couldn't find 'usr/bin/nwam-manager-properties' in any of the specified search directories:
>         /ws/toasty/oi-userland/components/openindiana/nwam-manager
>         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build
>         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386
>         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/mangled
> ```
> 
> But i have files in the `i86` subdirectory
> 
> ```
> ls -alh $WORKSPACE/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/usr/bin/i86/
> total 6
> drwxr-xr-x   2 toasty   builders       3 Aug 22 17:55 .
> drwxr-xr-x   3 toasty   builders       3 Aug 22 17:51 ..
> -rwxr-xr-x   1 toasty   builders   1.16K Aug 22 17:55 nwam-manager-properties
> ```

Your failure is not related to this PR, but to https://github.com/OpenIndiana/oi-userland/pull/9107.  I'm looking at it...

**Comment by mtelka** [comment]
> > Are you building with your prefer 32bit patch? I get
> > ```
> > Couldn't find 'usr/bin/nwam-manager-properties' in any of the specified search directories:
> >         /ws/toasty/oi-userland/components/openindiana/nwam-manager
> >         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build
> >         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386
> >         /ws/toasty/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/mangled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But i have files in the `i86` subdirectory
> > ```
> > ls -alh $WORKSPACE/oi-userland/components/openindiana/nwam-manager/build/prototype/i386/usr/bin/i86/
> > total 6
> > drwxr-xr-x   2 toasty   builders       3 Aug 22 17:55 .
> > drwxr-xr-x   3 toasty   builders       3 Aug 22 17:51 ..
> > -rwxr-xr-x   1 toasty   builders   1.16K Aug 22 17:55 nwam-manager-properties
> > ```
> 
> Your failure is not related to this PR, but to [OpenIndiana/oi-userland#9107](https://github.com/OpenIndiana/oi-userland/pull/9107). I'm looking at it...

Wait.  Did you try to build with https://github.com/OpenIndiana/oi-userland/pull/9107?  If not, then you should.  Without oi-userland's PR#9107 such failures are not surprising.  Thanks.

**Comment by mtelka** [comment]
The background is that `nwam-manager` is currently not buildable via [oi-userland](https://github.com/OpenIndiana/oi-userland) for two reasons:

* a problem fixed in this PR
* problem with `BUILD_BITS` fixed as a side effect of https://github.com/OpenIndiana/oi-userland/pull/9107

So to have `nwam-manager` buildable via [oi-userland](https://github.com/OpenIndiana/oi-userland) we need both PRs merged.

**Pull request merged**
